import { QueryProvider, ShadCnSidebarProvider } from '@/providers';
import { AppSidebar } from '@/client/sidebar';
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

import CustomSidebarTrigger from '@/client/sidebar/CustomSidebarTrigger';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ShadCnSidebarProvider>
            <AppSidebar />
            <main className="flex-1">
              <CustomSidebarTrigger />
              {children}
            </main>
          </ShadCnSidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
